[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["B", "E", "F", "I", "UP"]
ignore = ["W505"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = false
warn_redundant_casts = true
warn_return_any = false
disallow_incomplete_defs = true
check_untyped_defs = true
explicit_package_bases = true
namespace_packages = true
exclude = ['^venv/']
